// Core data types for Declutter App MVP

export interface DeclutterItem {
  id: string; // Auto-generated globally unique string by Dexie Cloud
  realmId?: string; // Optional realm ID for sharing (null for private items)
  createdAt: string; // ISO timestamp
  updatedAt: string; // ISO timestamp
  photo: Blob; // Compressed image
  thumbnail: Blob; // Small preview for lists

  // Name fields
  nameJapaneseSpecific: string; // Brand + details in Japanese
  nameEnglishSpecific: string; // Brand + details in English
  nameJapaneseGeneric: string; // Generic name in Japanese
  nameEnglishGeneric: string; // Generic name in English

  description: string;
  category: string;
  condition: "new" | "like_new" | "good" | "fair" | "poor";
  quantity: number; // Number of items (default: 1)

  // Price estimation with separate market types
  onlineAuctionPriceJPY: {
    low: number;
    high: number;
    confidence: number; // 0-1 scale
  };
  thriftShopPriceJPY: {
    low: number;
    high: number;
    confidence: number; // 0-1 scale
  };

  recommendedAction: "keep" | "trash" | "thrift" | "online" | "donate";
  actionRationale?: string; // Why this action was recommended
  marketplaces: string[]; // ["Mercari", "Yahoo Auctions", etc.]
  searchQueries: string[]; // Suggested search terms for marketplaces
  specialNotes: string | null; // Can be null if no special considerations
  keywords: string[]; // For internal search

  // Disposal cost field
  disposalCostJPY?: number; // For oversized items (粗大ごみ)

  municipalityCode?: string; // For location-specific disposal info
}

// Database interface that extends DeclutterItem for Dexie
export type DeclutterItemDB = DeclutterItem;

// Dashboard summary calculations interface
export interface DashboardSummary {
  totalItems: number;
  itemsByAction: {
    keep: number;
    online: number;
    thrift: number;
    donate: number;
    trash: number;
  };
  itemsByCategory: Record<string, number>;
  estimatedResaleValue: {
    low: number;
    high: number;
    averageConfidence: number;
  };
  estimatedDisposalCost: number;
}

// API response types
export interface AnalyzeApiResponse {
  success: boolean;
  data?: Omit<
    DeclutterItem,
    "id" | "createdAt" | "updatedAt" | "photo" | "thumbnail" | "quantity"
  >;
  error?: string;
}

// Utility types for form handling
export type DeclutterItemFormData = Omit<
  DeclutterItem,
  "id" | "createdAt" | "updatedAt"
>;

// Blob utility functions
export function getBlobUrl(blob: Blob): string {
  return URL.createObjectURL(blob);
}

export function revokeBlobUrl(url: string): void {
  URL.revokeObjectURL(url);
}

// Municipality data structure for disposal information
export interface Municipality {
  code: string; // Unique municipality code
  name: string; // English name
  nameJapanese: string; // Japanese name
  sodaiGomiUrl?: string; // Link to oversized waste disposal info
  kadenRecycleUrl?: string; // Link to appliance recycling info
  generalWasteUrl?: string; // General waste disposal info
  notes?: string; // Municipality-specific disposal notes
}

// Category-specific disposal information
export interface DisposalInfo {
  municipalityCode: string;
  category: string;
  urls: string[];
  notes?: string;
  estimatedFee?: number; // JPY
}

// Storage quota information
export interface StorageQuota {
  available: number;
  used: number;
  percentage: number;
}

// Image compression quality options
export type ImageQuality = "standard" | "lite";

// Export data types
export type ExportFormat = "csv";

export interface ExportOptions {
  format: ExportFormat;
  includeImages: boolean;
  selectedIds?: string[];
}

// Dexie Cloud Realm and Member Types for Family Sharing

export interface DeclutterRealm {
  realmId: string; // Auto-generated by Dexie Cloud
  name: string; // Human-readable name like "Tanaka Family"
  owner: string; // User ID of the realm creator
  createdAt: string; // ISO timestamp
  description?: string; // Optional description
}

export interface DeclutterMember {
  id?: string; // Auto-generated by Dexie Cloud
  realmId: string; // Realm this member belongs to
  userId?: string; // User ID of the member (set by system)
  name?: string; // Display name (e.g., "Mom", "Sister Yuki")
  email?: string; // Email for invitation
  invite?: boolean; // True when invitation is pending
  invited?: Date; // Invitation timestamp (system-managed)
  accepted?: Date; // Acceptance timestamp (system-managed)
  rejected?: Date; // Rejection timestamp (system-managed)
  roles?: string[]; // Array of role names ["owner"] or ["member"]
}

// Helper types for realm operations
export interface CreateRealmRequest {
  name: string;
  description?: string;
}

export interface InviteMemberRequest {
  email: string;
  name: string;
  realmId: string;
}

export interface RealmSummary {
  realm: DeclutterRealm;
  members: DeclutterMember[];
  itemCount: number;
  isOwner: boolean;
}
